# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open API Enforcer
email: email@email.com
description: > # this means to ignore newlines until "baseurl:"
  The Open API Enforcer is a library that provides tools that make it easy to work with the Open API Specification.
  It can validate your OAS documents; serialize, deserialize, and validate against OAS schemas;
  identify the operation associated with a request; parse, deserialize, and validate request parameters;
  facilitate response building;
  generate random valid values for a schema;
  and provides a plugin environment for custom document validation and extended functionality, including custom data type formats.
baseurl: "/openapi-enforcer" # the subpath of your site, e.g. /blog
url: "https://byu-oit.github.io"
github_username: github

# Build settings
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

plugins:
  - jekyll-toc
